version: "3.8"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: arbeitszeit-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/worktime.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - arbeitszeit-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arbeitszeit-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - arbeitszeit-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: arbeitszeit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - arbeitszeit-network

networks:
  arbeitszeit-network:
    driver: bridge

volumes:
  data:
    driver: local